services:
  postgres:
    image: postgres:15
    container_name: postgres_crm
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d
    networks:
      - data_network

  clickhouse:
    # Pinned version để tránh breaking changes khi ClickHouse release version mới
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: clickhouse
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123" # HTTP port
      - "${CLICKHOUSE_NATIVE_PORT:-9000}:9000" # Native port
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - data_network

  superset:
    image: apache/superset:4.0.0
    container_name: superset_instacart
    ports:
      - "${SUPERSET_PORT:-8088}:8088"
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    depends_on:
      - clickhouse
    networks:
      - data_network
    user: "root"
    command: >
      bash -c "
      pip install clickhouse-connect &&
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname Superset --email admin@example.com --password admin &&
      superset init &&
      /usr/bin/run-server.sh"

volumes:
  clickhouse_data:

networks:
  data_network:
    driver: bridge
