# Sử dụng image chính thức của Apache Airflow
FROM apache/airflow:2.9.1

# Cài đặt thêm thư viện hệ thống cần thiết (nếu có)
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         git \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Chuyển về user airflow để cài đặt thư viện Python
USER airflow

# Cài đặt dbt-core và dbt-clickhouse
RUN pip install --no-cache-dir "dbt-core>=1.7.0" "dbt-clickhouse>=1.7.0"
